### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by kgrubb**
Fix a small typo in buttons selection in settings app

### CODE REVIEW

**Comment by Akianonymus** [comment]
use Gerrit

**Comment by kgrubb** [comment]
^ can you give me some quick info on where or how to do that? I'm not familiar with gerrit.

**Comment by Akianonymus** [comment]
@kgrubb Google maybe

Gerrit link :  http://gerrit.pixysos.org/

**Comment by kgrubb** [comment]
thanks for the link, i'll take a look

**Pull request closed without merging**
